[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo no-build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
